In [3]:
import gdown
url='https://drive.google.com/uc?id=1gPFE1ozD6Y-M4fBa0dy4USdu426YMCB6'
url_drop='https://drive.google.com/uc?id=1SvkpRftjiYGBRt1ZM2Ert22gVxMiQJO6'
filename='PtlibraryData(week7).csv'
filename_drop='PtlibraryData_drop(week7).csv'
gdown.download(url, filename, quiet = False)
gdown.download(url_drop, filename_drop, quiet = False)

Downloading...
From: https://drive.google.com/uc?id=1gPFE1ozD6Y-M4fBa0dy4USdu426YMCB6
To: /content/PtlibraryData(week7).csv
100%|██████████| 30.8M/30.8M [00:00<00:00, 33.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SvkpRftjiYGBRt1ZM2Ert22gVxMiQJO6
To: /content/PtlibraryData_drop(week7).csv
100%|██████████| 127k/127k [00:00<00:00, 34.8MB/s]

'PtlibraryData_drop(week7).csv'

In [4]:
import pandas as pd

ns_df = pd.read_csv(filename_drop, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,NaN,199.1,1,0,2023-03-30,NaN
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.7,1,0,2023-03-30,NaN
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.6,1,0,2023-03-30,NaN
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.7,1,0,2023-03-30,NaN
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.7,1,0,2023-03-30,NaN

대괄호 사용

In [8]:
ns_df.loc[0:1,['도서명', '대출건수']]

          도서명  대출건수
0    세이노의 가르침     0
1  서울대생의 비밀과외     0

In [14]:
ns_book = ns_df.loc[:, '번호':'주제분류번호']
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,NaN,199.1
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.7
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.6
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.7
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.7

In [17]:
print(ns_df.columns)
ns_df.columns != 'Unnamed: 13'

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [20]:
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns]
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.7,1,0,2023-03-30

In [21]:
selected_columns = ns_df.columns != '권'
ns_book = ns_df.loc[:, selected_columns]
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,199.1,1,0,2023-03-30,NaN
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,373.7,1,0,2023-03-30,NaN
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,376.6,1,0,2023-03-30,NaN
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,813.7,1,0,2023-03-30,NaN
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,813.7,1,0,2023-03-30,NaN

In [24]:
ns_book = ns_df.drop('Unnamed: 13', axis=1)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.7,1,0,2023-03-30

In [25]:
ns_book.drop('권', axis=1, inplace=True)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,813.7,1,0,2023-03-30

In [26]:
ns_book=ns_df.dropna(axis=1)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,813.7,1,0,2023-03-30

In [28]:
ns_book=ns_df.dropna(axis=1, how='all')
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.791170e+12,NaN,0.0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.7,1,0,2023-03-30

In [30]:
ns_tmp=ns_book.drop([0,3])
ns_tmp.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.791130e+12,NaN,1.0,NaN,373.70,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.60,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.70,1,0,2023-03-30
5,6,환상서점,소서림 지음,해피북스투유,2023,9.791160e+12,NaN,0.0,NaN,813.70,1,0,2023-03-30
6,7,한국형 가치투자,"최준철,김민국 [공]지음",이콘,2023,9.791190e+12,NaN,0.0,NaN,327.85,1,0,2023-03-30

In [31]:
ns_tmp = ns_book[2:]
ns_tmp.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.791170e+12,NaN,1.0,NaN,376.60,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.791170e+12,NaN,4.0,NaN,813.70,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.788950e+12,NaN,0.0,NaN,813.70,1,0,2023-03-30
5,6,환상서점,소서림 지음,해피북스투유,2023,9.791160e+12,NaN,0.0,NaN,813.70,1,0,2023-03-30
6,7,한국형 가치투자,"최준철,김민국 [공]지음",이콘,2023,9.791190e+12,NaN,0.0,NaN,327.85,1,0,2023-03-30

In [34]:
ns_book = pd.read_csv(filename, low_memory=False)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.79117E+12,NaN,0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.79113E+12,NaN,1,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.79117E+12,NaN,1,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.79117E+12,NaN,4,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30

In [35]:
selected_rows=ns_book['출판사']=='문학동네'
print(selected_rows)

0         False
1         False
2         False
3         False
4          True
          ...
227830    False
227831    False
227832    False
227833    False
227834    False
Name: 출판사, Length: 227835, dtype: bool

In [36]:
ns_tmp=ns_book[selected_rows]
ns_tmp.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30
8,9,트러스트,에르난 디아스 지음;강동혁 옮김,문학동네,2023,9.78895E+12,NaN,0,NaN,843.6,1,0,2023-03-30
14,15,사랑의 꿈,손보미 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30
18,19,양아치의 스피치,네온비 글;김인정 그림,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30
40,41,쇼코의 미소,최은영 지음,문학동네,2016,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30

In [40]:
ns_tmp=ns_book[ns_book['대출건수']>300]
ns_tmp.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
135049,135050,드래곤 라자,이영도 지음,황금가지,1998,9.78898E+12,NaN,0,1,813.6,1,303,2007-10-11
177765,177766,해리포터와 불사조 기사단,조앤 K. 롤링 지음;최인자 옮김,문학수첩,2003,9.78898E+12,9.788980e+12,0,53,843,3,319,2003-12-17
177766,177767,해리포터와 불사조 기사단,조앤 K. 롤링 지음;최인자 옮김,문학수첩,2003,9.78898E+12,9.788980e+12,NaN,52,843,3,364,2003-12-17
177767,177768,해리포터와 불사조기사단,조앤.K.롤링 지음;최인자 옮김,문학수첩,2003,9.78898E+12,9.788980e+12,0,51,843,3,349,2003-12-17

In [43]:
dup_list=['도서명','저자','ISBN']
sum(ns_book.duplicated(subset=dup_list))

31669

In [51]:
count_df=ns_book[['도서명', '저자', 'ISBN', '대출건수']]
'''
group_df=count_df.groupby(by=['도서명','저자','ISBN'], dropna=False)
loan_count=group_df.sum()
'''

loan_count=count_df.groupby(by=['도서명','저자','ISBN'], dropna=False).sum()
loan_count.head()

                                                                                대출건수
도서명                                             저자                 ISBN
 (New)대한민국에서 가장 쉬운 문법책                          김창배;김현구 공저         9.78892E+12    26
 (新)한자 千字사전                                     이관배;임동욱;홍진용 지음     9.78891E+12     0
 ?쪽의 마이 다이어리=My diary                           고훈 글·그림            9.78899E+12    30
 My beautiful girl, Indigo : 인디고 서원, 내 청춘의 오아시스 아람샘;인디고 아이들[공]찍고 씀 9.78896E+12     0
 나는 SNS 전문가가 될 거야!                              Team. 신화 글·그림      9.79119E+12     3

In [56]:
dup_rows=ns_book.duplicated(subset=['도서명','저자','ISBN'])
unique_rows=~dup_rows
ns_book3=ns_book[unique_rows].copy()
ns_book3.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,세이노의 가르침,세이노 지음,데이원,2023,9.79117E+12,NaN,0,NaN,199.1,1,0,2023-03-30
1,2,서울대생의 비밀과외,"소린TV,안소린 [공]지음",다산에듀,2023,9.79113E+12,NaN,1,NaN,373.7,1,0,2023-03-30
2,3,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,센시오,2023,9.79117E+12,NaN,1,NaN,376.6,1,0,2023-03-30
3,4,당연하게도 나는 너를,이꽃님 지음,우리학교,2023,9.79117E+12,NaN,4,NaN,813.7,1,0,2023-03-30
4,5,고요한 우연,김수빈 지음,문학동네,2023,9.78895E+12,NaN,0,NaN,813.7,1,0,2023-03-30

In [57]:
ns_book3.set_index(['도서명','저자','ISBN'], inplace=True)
ns_book3.head()

,,,번호,출판사,발행년도,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
도서명,저자,ISBN,,,,,,,,,,
세이노의 가르침,세이노 지음,9.79117E+12,1,데이원,2023,NaN,0,NaN,199.1,1,0,2023-03-30
서울대생의 비밀과외,"소린TV,안소린 [공]지음",9.79113E+12,2,다산에듀,2023,NaN,1,NaN,373.7,1,0,2023-03-30
(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,9.79117E+12,3,센시오,2023,NaN,1,NaN,376.6,1,0,2023-03-30
당연하게도 나는 너를,이꽃님 지음,9.79117E+12,4,우리학교,2023,NaN,4,NaN,813.7,1,0,2023-03-30
고요한 우연,김수빈 지음,9.78895E+12,5,문학동네,2023,NaN,0,NaN,813.7,1,0,2023-03-30

In [63]:
ns_book3.update(loan_count)

In [64]:
ns_book4=ns_book3.reset_index()
ns_book4.head()

,도서명,저자,ISBN,번호,출판사,발행년도,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,세이노의 가르침,세이노 지음,9.79117E+12,1,데이원,2023,NaN,0,NaN,199.1,1,0.0,2023-03-30
1,서울대생의 비밀과외,"소린TV,안소린 [공]지음",9.79113E+12,2,다산에듀,2023,NaN,1,NaN,373.7,1,0.0,2023-03-30
2,(현직 고등학교 선생님들이 직접 고른) 생기부 필독서 100,주경아 외 지음,9.79117E+12,3,센시오,2023,NaN,1,NaN,376.6,1,0.0,2023-03-30
3,당연하게도 나는 너를,이꽃님 지음,9.79117E+12,4,우리학교,2023,NaN,4,NaN,813.7,1,0.0,2023-03-30
4,고요한 우연,김수빈 지음,9.78895E+12,5,문학동네,2023,NaN,0,NaN,813.7,1,0.0,2023-03-30

In [65]:
sum(ns_book['대출건수']>300)

4

In [66]:
sum(ns_book4['대출건수']>300)

324

In [69]:
ns_book4=ns_book4[ns_book.columns]
ns_book4.to_csv('ns_book4.csv', index=False)